// This file will be auto-generated by Supabase CLI
// Run: npm run db:types
// For now, we define types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          display_name: string | null;
          phone: string | null;
          points: number;
          lifetime_points: number;
          birthday: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name?: string | null;
          phone?: string | null;
          points?: number;
          lifetime_points?: number;
          birthday?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string | null;
          phone?: string | null;
          points?: number;
          lifetime_points?: number;
          birthday?: string | null;
          updated_at?: string;
        };
      };
      menu_items: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          price: number;
          category: 'coffee' | 'boba' | 'smoothie' | 'food' | 'specialty';
          subcategory: string | null;
          image_url: string | null;
          is_available: boolean;
          is_featured: boolean;
          is_seasonal: boolean;
          allergens: string[] | null;
          caffeine_level: 'none' | 'low' | 'medium' | 'high' | null;
          calories: number | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          price: number;
          category: 'coffee' | 'boba' | 'smoothie' | 'food' | 'specialty';
          subcategory?: string | null;
          image_url?: string | null;
          is_available?: boolean;
          is_featured?: boolean;
          is_seasonal?: boolean;
          allergens?: string[] | null;
          caffeine_level?: 'none' | 'low' | 'medium' | 'high' | null;
          calories?: number | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          description?: string | null;
          price?: number;
          category?: 'coffee' | 'boba' | 'smoothie' | 'food' | 'specialty';
          subcategory?: string | null;
          image_url?: string | null;
          is_available?: boolean;
          is_featured?: boolean;
          is_seasonal?: boolean;
          allergens?: string[] | null;
          caffeine_level?: 'none' | 'low' | 'medium' | 'high' | null;
          calories?: number | null;
          sort_order?: number;
          updated_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string | null;
          event_type: 'tournament' | 'social' | 'launch' | 'private' | 'recurring';
          event_date: string;
          end_date: string | null;
          fee: number;
          max_capacity: number | null;
          current_registrations: number;
          image_url: string | null;
          is_featured: boolean;
          is_recurring: boolean;
          recurrence_pattern: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description?: string | null;
          event_type: 'tournament' | 'social' | 'launch' | 'private' | 'recurring';
          event_date: string;
          end_date?: string | null;
          fee?: number;
          max_capacity?: number | null;
          current_registrations?: number;
          image_url?: string | null;
          is_featured?: boolean;
          is_recurring?: boolean;
          recurrence_pattern?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          title?: string;
          slug?: string;
          description?: string | null;
          event_type?: 'tournament' | 'social' | 'launch' | 'private' | 'recurring';
          event_date?: string;
          end_date?: string | null;
          fee?: number;
          max_capacity?: number | null;
          current_registrations?: number;
          image_url?: string | null;
          is_featured?: boolean;
          is_recurring?: boolean;
          recurrence_pattern?: string | null;
          updated_at?: string;
        };
      };
      event_registrations: {
        Row: {
          id: string;
          event_id: string;
          user_id: string;
          status: 'registered' | 'waitlist' | 'cancelled' | 'attended';
          payment_status: 'pending' | 'paid' | 'refunded';
          notes: string | null;
          registered_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          user_id: string;
          status?: 'registered' | 'waitlist' | 'cancelled' | 'attended';
          payment_status?: 'pending' | 'paid' | 'refunded';
          notes?: string | null;
          registered_at?: string;
        };
        Update: {
          status?: 'registered' | 'waitlist' | 'cancelled' | 'attended';
          payment_status?: 'pending' | 'paid' | 'refunded';
          notes?: string | null;
        };
      };
      orders: {
        Row: {
          id: string;
          user_id: string | null;
          order_number: string;
          status: 'pending' | 'confirmed' | 'preparing' | 'ready' | 'completed' | 'cancelled';
          order_type: 'pickup' | 'dine_in';
          subtotal: number;
          tax: number;
          total: number;
          points_earned: number;
          points_redeemed: number;
          estimated_ready_at: string | null;
          completed_at: string | null;
          square_order_id: string | null;
          square_payment_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          order_number: string;
          status?: 'pending' | 'confirmed' | 'preparing' | 'ready' | 'completed' | 'cancelled';
          order_type: 'pickup' | 'dine_in';
          subtotal: number;
          tax: number;
          total: number;
          points_earned?: number;
          points_redeemed?: number;
          estimated_ready_at?: string | null;
          completed_at?: string | null;
          square_order_id?: string | null;
          square_payment_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'pending' | 'confirmed' | 'preparing' | 'ready' | 'completed' | 'cancelled';
          points_earned?: number;
          points_redeemed?: number;
          estimated_ready_at?: string | null;
          completed_at?: string | null;
          square_order_id?: string | null;
          square_payment_id?: string | null;
          updated_at?: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          menu_item_id: string | null;
          name: string;
          quantity: number;
          unit_price: number;
          customizations: Json | null;
          special_instructions: string | null;
          subtotal: number;
        };
        Insert: {
          id?: string;
          order_id: string;
          menu_item_id?: string | null;
          name: string;
          quantity?: number;
          unit_price: number;
          customizations?: Json | null;
          special_instructions?: string | null;
          subtotal: number;
        };
        Update: {
          quantity?: number;
          customizations?: Json | null;
          special_instructions?: string | null;
          subtotal?: number;
        };
      };
      products: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          price: number;
          category: 'tcg' | 'accessories' | 'dice' | 'merch' | 'snacks';
          subcategory: string | null;
          sku: string | null;
          stock_quantity: number;
          low_stock_threshold: number;
          image_url: string | null;
          is_available: boolean;
          is_preorder: boolean;
          release_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          price: number;
          category: 'tcg' | 'accessories' | 'dice' | 'merch' | 'snacks';
          subcategory?: string | null;
          sku?: string | null;
          stock_quantity?: number;
          low_stock_threshold?: number;
          image_url?: string | null;
          is_available?: boolean;
          is_preorder?: boolean;
          release_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          description?: string | null;
          price?: number;
          category?: 'tcg' | 'accessories' | 'dice' | 'merch' | 'snacks';
          subcategory?: string | null;
          sku?: string | null;
          stock_quantity?: number;
          low_stock_threshold?: number;
          image_url?: string | null;
          is_available?: boolean;
          is_preorder?: boolean;
          release_date?: string | null;
          updated_at?: string;
        };
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          menu_item_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          menu_item_id: string;
          created_at?: string;
        };
        Update: never;
      };
      points_transactions: {
        Row: {
          id: string;
          user_id: string;
          amount: number;
          type: 'purchase' | 'redemption' | 'bonus' | 'referral' | 'event' | 'adjustment';
          description: string | null;
          order_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          amount: number;
          type: 'purchase' | 'redemption' | 'bonus' | 'referral' | 'event' | 'adjustment';
          description?: string | null;
          order_id?: string | null;
          created_at?: string;
        };
        Update: never;
      };
      rewards: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          points_required: number;
          reward_type: 'free_item' | 'discount' | 'percentage_off';
          reward_value: Json;
          is_active: boolean;
          sort_order: number;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          points_required: number;
          reward_type: 'free_item' | 'discount' | 'percentage_off';
          reward_value: Json;
          is_active?: boolean;
          sort_order?: number;
        };
        Update: {
          name?: string;
          description?: string | null;
          points_required?: number;
          reward_type?: 'free_item' | 'discount' | 'percentage_off';
          reward_value?: Json;
          is_active?: boolean;
          sort_order?: number;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

// Convenience types
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

// Specific entity types for easier use
export type Profile = Tables<'profiles'>;
export type MenuItem = Tables<'menu_items'>;
export type Event = Tables<'events'>;
export type EventRegistration = Tables<'event_registrations'>;
export type Order = Tables<'orders'>;
export type OrderItem = Tables<'order_items'>;
export type Product = Tables<'products'>;
export type Favorite = Tables<'favorites'>;
export type PointsTransaction = Tables<'points_transactions'>;
export type Reward = Tables<'rewards'>;
